# Generated by Django 3.2 on 2021-04-28 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100)),
                ('ep_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default='#', upload_to='images')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('season', models.DecimalField(decimal_places=0, max_digits=10)),
                ('episode', models.DecimalField(decimal_places=0, max_digits=10)),
                ('link', models.URLField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('eps_link', models.ManyToManyField(to='projects.Episodes')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('videos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.videos')),
            ],
        ),
    ]
