# Generated by Django 3.2 on 2021-04-28 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videos',
            name='link',
        ),
    ]
