# Generated by Django 3.2 on 2021-04-28 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_videos_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videos',
            name='episode',
        ),
    ]
