# Generated by Django 3.2 on 2021-04-28 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_videos_episode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='season',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
