# Generated by Django 3.2 on 2021-04-28 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_videos_season'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('genre', models.TextField(blank=True, null=True)),
                ('author', models.TextField(blank=True, null=True)),
                ('release', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
